### ISSUE TITLE
Missing hw08 grade

### ISSUE THREAD

**Issue by rasiimwe** [STAT545-UBC-students/hw08-rasiimwe#3]
@ChadFibke @Rashedul @sherrie9 @hsmohammed 

Hi awesome TAs,

I haven't received my hw08 grade yet. Kindly help me look into this.

Thanks, and thanks for the great job done helping us through STAT 545/7M. Your comments, guidance, patience and advise were immeasurable and very valuable 🥇 👏 👏 

Many thanks
Rebecca

**Comment by Rashedul** [comment]
Just posted your grade. Thanks!

**Comment by rasiimwe** [comment]
Thank you very much @Rashedul
